#!/usr/bin/env python3
import json
from datetime import datetime

# 读取搜索结果
with open("duplicates.json") as f:
    data = json.load(f)

# 确定建议
top_score = data["top_5"][0]["similarity"] if data["top_5"] else 0
if top_score >= 15:
    recommendation = "review_existing"
    reason = "Found highly similar issue (score >= 15)"
elif top_score >= 10:
    recommendation = "review_existing"
    reason = "Found moderately similar issue (score >= 10)"
else:
    recommendation = "likely_new"
    reason = "No similar issues found (top score < 10)"

top_issue = f"#{data['top_5'][0]['number']}" if data['top_5'] else "N/A"

# 生成 markdown 报告
report = f"""# CIRCT Bug Duplicate Check Report

**Date**: {datetime.now().isoformat()}  
**Testcase ID**: 260128-00000ac8  

## Executive Summary

| Metric | Value |
|--------|-------|
| **Recommendation** | `{recommendation}` |
| **Top Similarity Score** | {top_score:.1f}/20 |
| **Most Similar Issue** | {top_issue} |
| **Total Results Found** | {data['total_results']} |

### Analysis Result
{reason}

---

## Search Methodology

### Keywords Extracted
- **Tool**: {data['keywords']['tool']}
- **Pass**: {data['keywords']['pass']}
- **Crash Type**: {data['keywords']['crash_type']}
- **Dialect**: {data['keywords']['dialect']}
- **Function**: {data['keywords']['function']}
- **Error Pattern**: {data['keywords']['cast_error']}
- **Type Issue**: {data['keywords']['struct_type']}

### Search Queries Used
"""

for query in data["search_queries"]:
    report += f"- `{query}`\n"

report += """
### Similarity Scoring System
| Score | Classification | Criteria |
|-------|-----------------|----------|
| 20 | Perfect Match | Same function, same error type |
| 15 | High Relevance | Same pass, different error |
| 10 | Moderate | Same dialect, related operations |
| 5 | Weak | Same error type or tool |
| 0 | No Match | No matching keywords |

---

## Top 5 Most Similar Issues

"""

for i, issue in enumerate(data["top_5"], 1):
    report += f"""### {i}. Issue #{issue['number']}
**Title**: {issue['title']}  
**State**: {issue['state']}  
**Similarity Score**: {issue['similarity']:.1f}/20  
**Matched Queries**: {', '.join([f'`{q}`' for q in issue['queries']])}  
**Labels**: {', '.join([f'`{label['name']}`' for label in issue.get('labels', [])]) if issue.get('labels') else 'None'}  

"""

report += """---

## Detailed Results

All {0} results found are listed below (sorted by similarity):

""".format(data['total_results'])

for issue in data["all_results"]:
    report += f"- **#{issue['number']}** ({issue['similarity']:.1f}pts) - {issue['title']} ({issue['state']})\n"

report += f"""

---

## Recommendation Details

**Decision**: `{recommendation.upper()}`

"""

if recommendation == "review_existing":
    report += f"""
**Reason**: The top similar issue (#{data['top_5'][0]['number']}) has a similarity score of {top_score:.1f}/20, indicating potential overlap.

**Action Items**:
1. Review issue #{data['top_5'][0]['number']}: {data['top_5'][0]['title']}
2. Compare error signatures and stack traces
3. Determine if this is a duplicate or a related but distinct issue
4. Check if the issue is already in progress or fixed in latest main branch

**Next Steps**:
- If confirmed duplicate: Link issues and close the new one
- If related but distinct: Document the relationship and proceed with separate fix
- If unrelated: Proceed with new issue report
"""
else:
    report += f"""
**Reason**: No issues found with high similarity to the current crash (top score {top_score:.1f}/20 < 10).

**Action Items**:
1. Create a new GitHub issue with the full crash report
2. Include reproduction steps and minimal test case
3. Reference any relevant related issues (if any)

**Suggested Title Format**:
`[Arc] InferStateProperties assertion failure with packed struct in struct array`

**Suggested Labels**:
- `bug`
- `Arc` (dialect)
- `crash`
"""

report += f"""

---

## Metadata
- **Search Timestamp**: {data['timestamp']}
- **Total Issues Analyzed**: {len(data['all_results'])}
- **Queries Executed**: {len(data['search_queries'])}

Generated by: check-duplicates-worker
"""

# 保存报告
with open("duplicates.md", "w") as f:
    f.write(report)

print("✅ Report generated: duplicates.md")
print("\n" + "="*60)
print("FINAL REPORT")
print("="*60)
print(f"recommendation: {recommendation}")
print(f"top_score: {top_score:.1f}")
print(f"top_issue: {top_issue}")
print("="*60)

